//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cash
    {
        public int ID { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<decimal> Costs { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Cashless { get; set; }
        public Nullable<decimal> Result { get; set; }
    }
}
